package com.carapp.backend.model.enums

enum class TransmissionType {
    `1-speed direct drive`,
    `10-speed automatic`,
    `10-speed shiftable automatic`,
    `2-speed`,
    `2-speed automatic`,
    `3-speed automatic`,
    `4-speed automatic`,
    `4-speed manual`,
    `4-speed shiftable automatic`,
    `5-speed automated manual`,
    `5-speed automatic`,
    `5-speed manual`,
    `5-speed shiftable automatic`,
    `6-speed automated manual`,
    `6-speed automatic`,
    `6-speed manual`,
    `6-speed shiftable automatic`,
    `7-speed automated manual`,
    `7-speed automatic`,
    `7-speed manual`,
    `7-speed shiftable automatic`,
    `8-speed automated manual`,
    `8-speed automatic`,
    `8-speed shiftable automatic`,
    `9-speed automated manual`,
    `9-speed automatic`,
    `9-speed shiftable automatic`,
    `continuously variable-speed automatic`,
    `continuously variable-speed shiftable automatic`,
    `electrically variable-speed automatic`
}
