gg:
  jte:
    development-mode: true

spring:
  application:
    name: car-backend

  datasource:
    url: jdbc:postgresql://car-app-db-do-user-21214113-0.d.db.ondigitalocean.com:25060/defaultdb?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
