apiVersion: v1
kind: Service
metadata:
  name: car-app-backend-service
  namespace: car-app
spec:
  selector:
    app: car-app-backend
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
